name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Start backend in background
      run: npm start &
      working-directory: ./backend

    - name: Start frontend in background
      run: npm start &
      working-directory: ./frontend

    - name: Wait for applications to start
      run: sleep 10

    - name: Install Cypress dependencies
      run: npm install cypress --save-dev

    - name: Run Cypress tests
      run: npx cypress run
